version: '3.8'
services:
  api:
    build: ./messenger
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./messenger/:/usr/src/messenger/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
