# Generated by Django 3.2 on 2022-01-27 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000, verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL, verbose_name='Создатель сообщения')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщение',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ManyToManyField(related_name='archive_threads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи архивировшие диалог')),
                ('deleted', models.ManyToManyField(related_name='deleted_threads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи удалившие диалог')),
                ('participants', models.ManyToManyField(related_name='user_threads', to=settings.AUTH_USER_MODEL, verbose_name='Учатсники диалога')),
                ('push_notification', models.ManyToManyField(related_name='push_notification_threads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи с уведомлениями')),
            ],
            options={
                'verbose_name': 'Диалоги',
                'verbose_name_plural': 'Диалог',
            },
        ),
        migrations.CreateModel(
            name='MessagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thread/messages/2022/01/27', verbose_name='Фотография сообщения')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_photos', to='thread.message', verbose_name='Сообщение фотографии')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message_photos', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель фотографии')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages_photos', to='thread.thread', verbose_name='Диалог фотографии')),
            ],
            options={
                'verbose_name': 'Фотографии сообщений',
                'verbose_name_plural': 'Фотография сообщения',
                'db_table': 'message_photo',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='thread.thread'),
        ),
        migrations.AddField(
            model_name='message',
            name='who_deleted_the_message',
            field=models.ManyToManyField(related_name='user_deleted_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи удалившие сообщение'),
        ),
    ]
