# Generated by Django 3.2 on 2022-01-27 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_auto_20220127_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message_of_thread', to='thread.message', verbose_name='Последнее сообщение диалога'),
        ),
    ]
