# Generated by Django 3.2 on 2022-01-28 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0004_alter_messagephoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message_of_thread', to='thread.message', unique=True, verbose_name='Последнее сообщение диалога'),
        ),
    ]
