# Generated by Django 3.2 on 2022-01-28 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0005_alter_thread_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='archive',
            field=models.ManyToManyField(related_name='archive_threads', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи архивировавшие диалог'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_of_thread', to='thread.message', verbose_name='Последнее сообщение диалога'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(related_name='user_threads', to=settings.AUTH_USER_MODEL, verbose_name='Участники диалога'),
        ),
    ]
