# Generated by Django 3.2 on 2022-01-31 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0007_alter_messagephoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagephoto',
            name='image',
            field=models.ImageField(upload_to='thread/messages/2022/01/31', verbose_name='Фотография сообщения'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_of_thread', to='thread.message', verbose_name='Последнее сообщение диалога'),
        ),
    ]
