# Generated by Django 3.2 on 2022-02-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0008_auto_20220131_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagephoto',
            name='image',
            field=models.ImageField(upload_to='thread/messages/2022/02/02', verbose_name='Фотография сообщения'),
        ),
    ]
