# Generated by Django 3.2 on 2022-01-27 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название канала')),
                ('avatar', models.ImageField(default='static/messenger/images/default_image.jpg', upload_to='images/channel/avatars/2022/01/27')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание канала')),
                ('admins', models.ManyToManyField(related_name='admin_of_channels', to=settings.AUTH_USER_MODEL, verbose_name='Администраторы канала')),
                ('black_list', models.ManyToManyField(related_name='in_black_list_channels', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи в чёрном списке')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of_channels', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='channels', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи канала')),
            ],
            options={
                'verbose_name': 'Каналы',
                'verbose_name_plural': 'Канал',
                'db_table': 'channel',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст поста')),
                ('views', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='channel.channel', verbose_name='Канал поста')),
            ],
            options={
                'verbose_name': 'Посты каналов',
                'verbose_name_plural': 'Пост канала',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='videos/channel/posts/videos/2022/01/27', verbose_name='Видио поста')),
                ('description', models.TextField(max_length=500, verbose_name='Описание медиа для поисковиков')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_videos', to='channel.post', verbose_name='Видеозапись поста')),
            ],
            options={
                'verbose_name': 'Видио постов',
                'verbose_name_plural': 'Видио поста',
                'db_table': 'video_post',
            },
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/channel/posts/images/2022/01/27', verbose_name='Фотография поста')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='Описание медиа для поисковиков')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_images', to='channel.channel', verbose_name='Фотографии на какнале')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='channel.post', verbose_name='Фотографии в посте')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_post_images', to=settings.AUTH_USER_MODEL, verbose_name='Фотографии пользователя на каналах')),
            ],
            options={
                'verbose_name': 'Фотографии постов',
                'verbose_name_plural': 'Фотография поста',
                'db_table': 'image_post',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст коментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор коментария')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='channel.post', verbose_name='Пост коментария')),
            ],
            options={
                'verbose_name': 'Коментарии постов',
                'verbose_name_plural': 'Коментарий поста',
                'db_table': 'comment',
            },
        ),
    ]
