# Generated by Django 3.2 on 2022-01-29 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0002_auto_20220128_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарии постов', 'verbose_name_plural': 'Комментарий поста'},
        ),
        migrations.AlterField(
            model_name='channel',
            name='avatar',
            field=models.ImageField(default='static/messenger/images/default_image.jpg', upload_to='images/channel/avatars/2022/01/29'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='channel.post', verbose_name='Пост комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_images', to='channel.channel', verbose_name='Фотографии на канале'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(upload_to='images/channel/posts/images/2022/01/29', verbose_name='Фотография поста'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='image',
            field=models.ImageField(upload_to='videos/channel/posts/videos/2022/01/29', verbose_name='Видио поста'),
        ),
    ]
