# Generated by Django 3.2 on 2022-01-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_auto_20220129_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar',
            field=models.ImageField(default='static/messenger/images/default_image.jpg', upload_to='images/channel/avatars/2022/01/31'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(upload_to='images/channel/posts/images/2022/01/31', verbose_name='Фотография поста'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='image',
            field=models.ImageField(upload_to='videos/channel/posts/videos/2022/01/31', verbose_name='Видио поста'),
        ),
    ]
