# Generated by Django 3.2 on 2022-01-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='about_user',
            field=models.TextField(max_length=100, null=True, unique=True, verbose_name='Информация о пользователе'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='telephone',
            field=models.CharField(max_length=12, null=True, verbose_name='Телефон'),
        ),
    ]
