# Generated by Django 3.2 on 2022-01-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220127_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarimageprofile',
            name='image',
            field=models.ImageField(upload_to='images/account/avatars/2022/01/28', verbose_name='Фотография пользователя'),
        ),
    ]
