# Generated by Django 3.2 on 2022-01-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_avatarimageprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarimageprofile',
            name='image',
            field=models.ImageField(upload_to='images/account/avatars/2022/01/29', verbose_name='Фотография пользователя'),
        ),
    ]
