# Generated by Django 3.2 on 2022-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_avatarimageprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтверждён ли пользователь через почту'),
        ),
    ]
