# Generated by Django 3.2 on 2022-01-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_advuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='key',
            field=models.BigIntegerField(null=True, verbose_name='Ключ для подтверждения почты'),
        ),
    ]
