# Generated by Django 3.2 on 2022-01-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_advuser_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='key',
            field=models.BigIntegerField(db_index=True, null=True, verbose_name='Ключ для подтверждения почты'),
        ),
    ]
