# Generated by Django 3.2 on 2022-02-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_avatarimageprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarimageprofile',
            name='image',
            field=models.ImageField(upload_to='images/account/avatars/2022/02/02', verbose_name='Фотография пользователя'),
        ),
    ]
